-- Run this in Supabase → SQL Editor → New query → Run.
-- It creates the guestbook table and safe public access for it.

create table if not exists public.messages (
  id          bigint generated by default as identity primary key,
  name        text not null default 'Anonymous',
  message     text not null,
  created_at  timestamptz not null default now()
);

alter table public.messages enable row level security;

-- Anyone can read the guestbook.
drop policy if exists "read messages" on public.messages;
create policy "read messages"
  on public.messages for select
  using (true);

-- Anyone can add a message (it's a friendship guestbook, not a bank).
drop policy if exists "insert messages" on public.messages;
create policy "insert messages"
  on public.messages for insert
  with check (char_length(message) between 1 and 500);
